### ISSUE TITLE
Intro movie black

### ISSUE THREAD

**Issue by monreal** [h4mu/rott94#2] opened 2017-10-02 11:44 UTC
The intro movie (after starting a game) stays black. I hear the sound but I cannot see anything.

**Comment by h4mu** [comment] 2017-10-04 19:17
I can confirm it's the same for me and I don't remember ever seeing it work before but it didn't bother me that much tbh. I haven't looked for the cause yet and I probably won't have much time for it anytime soon but if you find a fix please create a pull request.

**Comment by h4mu** [comment] 2019-01-07 23:14
FIxed in latest commit, palettes work differently in SDL (and modern graphics libraries) than in good old DOS.

**Closed by h4mu** 2019-01-07 23:14 UTC
Labels: bug
